# Generated by Django 4.2.7 on 2023-11-12 04:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaymentHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subscription_id", models.CharField(max_length=255)),
                ("session_id", models.CharField(max_length=255)),
                ("product_id", models.CharField(max_length=255)),
                (
                    "amount_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("paid", models.BooleanField(default=False)),
            ],
        ),
    ]
