# Generated by Django 4.2.7 on 2023-11-12 04:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenthistory",
            name="amount_total",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
