# Generated by Django 4.2.7 on 2023-11-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("girls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="girls",
            name="background",
            field=models.CharField(
                choices=[
                    ("OR", "Orphan"),
                    ("HALF", "Half-Orphan"),
                    ("DEST", "Destitute"),
                    ("OTHER", "Other: Not in the orphanage"),
                ],
                default="OR",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="girls",
            name="current_location",
            field=models.CharField(
                choices=[
                    ("In-School", "In-school at orphanage"),
                    ("LOC2", "1-year vocational training"),
                    ("LOC3", "2-year vocational training"),
                    ("LOC3", "2-year junior college"),
                    ("LOC3", "3-year college"),
                    ("LOC3", "4-year college"),
                    ("LOC3", "3-year university"),
                    ("LOC3", "4-year university"),
                ],
                default="In-School",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="girls",
            name="dream_job",
            field=models.CharField(default="N/A"),
        ),
        migrations.AddField(
            model_name="girls",
            name="estimate_funding",
            field=models.DecimalField(decimal_places=2, default="0", max_digits=10),
        ),
        migrations.AddField(
            model_name="girls",
            name="explicit_permission",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="girls",
            name="personal_story",
            field=models.CharField(default=""),
        ),
        migrations.AddField(
            model_name="girls",
            name="picture_url",
            field=models.URLField(default=""),
        ),
        migrations.AddField(
            model_name="girls",
            name="time_to_self_sufficency",
            field=models.CharField(default="2000", max_length=4),
        ),
        migrations.AddField(
            model_name="girls",
            name="year_of_graduation",
            field=models.CharField(default="2000", max_length=4),
        ),
        migrations.AddField(
            model_name="girls",
            name="year_self_sufficiency",
            field=models.CharField(default="2000", max_length=4),
        ),
        migrations.AlterField(
            model_name="girls",
            name="year_joined_orphanage",
            field=models.CharField(),
        ),
    ]
